services:
  postgres:
    image: 'postgres:17'
    environment:
      POSTGRES_DB: board_game_collection
      POSTGRES_USER: board_game_collection
      POSTGRES_PASSWORD: board_game_collection
    ports:
      - '5432'
  minio:
    image: 'minio/minio:RELEASE.2025-10-15T17-29-55Z'
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
