apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: board-game-collection
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - board-game-collection.beefsack.com
      secretName: board-game-collection-tls
