apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress-host-patch.yaml
    target:
      kind: Ingress
      name: board-game-collection
  - path: ingress-tls-patch.yaml
    target:
      kind: Ingress
      name: board-game-collection

# CI updates these tags to the specific git SHA after a successful build.
images:
  - name: ghcr.io/beefsack/board-game-collection-api
    newTag: e6bf3e6457b48c389683029f31f151d1352028a8
  - name: ghcr.io/beefsack/board-game-collection-ui
    newTag: e6bf3e6457b48c389683029f31f151d1352028a8
