apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress-host-patch.yaml
    target:
      kind: Ingress
      name: board-game-collection
  - path: ingress-tls-patch.yaml
    target:
      kind: Ingress
      name: board-game-collection
  - path: minio-ingress-host-patch.yaml
    target:
      kind: Ingress
      name: board-game-collection-images

# CI updates these tags to the specific git SHA after a successful build.
images:
  - name: ghcr.io/beefsack/board-game-collection-api
    newTag: 4cbd59b4bcfe3a4e4d769139f27afc352955443f
  - name: ghcr.io/beefsack/board-game-collection-ui
    newTag: 4cbd59b4bcfe3a4e4d769139f27afc352955443f
