apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress-host-patch.yaml
    target:
      kind: Ingress
      name: board-game-collection

# CI updates these tags to the specific git SHA after a successful build.
images:
  - name: ghcr.io/beefsack/board-game-collection-api
    newTag: 3497a02d8b924660536090bd56fae053284b7d49
  - name: ghcr.io/beefsack/board-game-collection-ui
    newTag: 3497a02d8b924660536090bd56fae053284b7d49
