spring:
  application:
    name: board-game-collection
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  default-produces-media-type: application/json

app:
  minio:
    endpoint: http://localhost:9000
    bucket: board-games
    access-key: minioadmin
    secret-key: minioadmin
