apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: board-game-collection

resources:
  - namespace.yaml
  - api/deployment.yaml
  - api/service.yaml
  - ui/deployment.yaml
  - ui/service.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - minio/statefulset.yaml
  - minio/service.yaml
  - minio/ingress.yaml
  - ingress.yaml
